title:              An IoT Odyssey
email:
description:        A Developer's journey into the world of IoT and other sojourns along the way
author:             Chris Dinh
baseurl:            ""
url:                "https://aniotodyssey.com"

# Social Profiles
twitter_username:   ChrisDinhNZ
github_username:    ChrisDinhNZ
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           20
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
